export enum gameActionTypes {
  RUN_GAME = "RUN_GAME",
  STOP_GAME = "STOP_GAME",
  RESET_GAME = "RESET_GAME",
}

export enum botActionTypes {
  MOVE_BOT = "MOVE_BOT",
  ADD_BOT = "ADD_BOT",
  ADD_ITEM = "ADD_ITEM",
  RESET_BOTS = "RESET_BOTS",
  SELECT_BOT = "SELECT_BOT",
  UPDATE_BOT_LOCATION = "UPDATE_BOT_LOCATION",
  MAP_SETUP = "MAP_SETUP",
  SET_RANDOM_WALK = "SET_RANDOM_WALK",
}
